### PR TITLE
Update GET query string

### PR DESCRIPTION
**Pull request by booni3**
When using the cursor function like this:

```php
do {
    $res = $this->api()->tradeApi()->getOrderHistory([
        'category' => 'linear',
        'limit' => 10,
        'cursor' => $cursor
    ]);

    $orders = $orders->merge($res['list'])->unique('orderId');
    $cursor = $res['nextPageCursor'];

} while ($page++ < 3 && $cursor);
```

There are errors with the sha256 signing and authorization with bybit. To explain a bit further:

```php
// Works
$headers = $options['headers'];
$request = new Request('GET', 'https://api.bybit.com/v5/order/history?'.$encoded_params, $headers);
$res = $client->send($request);

// Works
$options2['headers'] = $options['headers'];
$res = $client->get('v5/order/history?'.$encoded_params, $options2);

// Doesn't WorkWorks
$res = $client->get('v5/order/history', $options);
```

The change I have made fixes the issue.

### CODE REVIEW

**Comment by denistorresan** [comment]
Hi @booni3 and thank you for your help!
I merged on master than on develop. Please use the develop branch for future PR.

**Comment by denistorresan** [comment]
hey @booni3 I found a problem with your code.
When I try to execute any API with GET parameters I get the following errors:

```
PHP Warning:  Undefined variable $encoded_params in bybit-php-api\src\ApiRequest.php on line 117
PHP Fatal error:  Uncaught ByBit\SDK\Exceptions\HttpException: The requested symbol is invalid. in bybit-php-api\src\ApiRequest.php:144
Stack trace:
#0 bybit-php-api\src\Api\MarketApi.php(22): ByBit\SDK\ApiRequest->call()
#1 bybit-php-api\examples\Market.php(13): ByBit\SDK\Api\MarketApi->getKline()
#2 {main}
  thrown in bybit-php-api\src\ApiRequest.php on line 144
```

May you give me a real example  just to test the problem?

PS: I updated the repo, please refer to develop branch

**Comment by booni3** [comment]
`The requested symbol is invalid` is coming from ByBit, right? 

Sorry the warning on `$encoded_params`, probably just need to add a check into that first to ensure it has been set.

Try running the following:

```php
        $api = new ByBitApi('', '');
        $orders = collect();
        $page = 1;
        $cursor = '';

        do {
            $res = $api->tradeApi()->getOrderHistory([
                'category' => 'linear',
                'limit' => 50,
                'cursor' => $cursor
            ]);

            $orders = $orders->merge($res['list'])->unique('orderId');
            $cursor = $res['nextPageCursor'];

        } while ($page++ < 10 && $cursor);
        
        return $orders;
```

**Comment by denistorresan** [comment]
Hi @booni3 now I understood the problem and I fixed with a little rework.
Please try my latest commit on develop, thank you!
PS: now is it possible to use composer to add the package on your project directly from packagist

**Comment by denistorresan** [comment]
@booni3 just an info, I moved the repo from my personal user to my organization.
New location is: goodmagma/bybit-php-api and now you can install with 

composer require goodmagma/bybit-php-api

**Pull request merged**
